# Generated by Django 3.2 on 2021-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
